apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applicationset
spec:
  generators:
  - git:
      repoURL: ssh://git@github.com/walton98/homelab3.git
      revision: HEAD
      directories:
      - path: "apps/*"
  template:
    metadata:
      name: "{{.path.basename}}"
    spec:
      project: default
      source:
        repoURL: ssh://git@github.com/walton98/homelab3.git
        targetRevision: main
        path: "{{.path.path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
