---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  namespace: jellyfin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
        name: jellyfin
    spec:
      nodeSelector:
        node-type: worker
      containers:
      - name: jellyfin
        image: jellyfin/jellyfin:{{- .Values.image.label }}
        ports:
        - containerPort: 8096
        volumeMounts:
        - name: config
          mountPath: /config
        - name: cache
          mountPath: /cache
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: longhorn-jellyfin-config-pvc
        - name: cache
          persistentVolumeClaim:
            claimName: longhorn-jellyfin-cache-pvc
