---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
        name: jellyfin
    spec:
      containers:
      - name: jellyfin
        image: lscr.io/linuxserver/jellyfin:{{- .Values.image.label }}
        ports:
        - containerPort: 8096
        volumeMounts:
        # https://docs.linuxserver.io/images/docker-jellyfin/#volume-mappings-v
        - name: config
          mountPath: /config
        - name: movies
          mountPath: /data/movies
        - name: tvshows
          mountPath: /data/tvshows
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: longhorn-jellyfin-config-pvc
        - name: movies
          persistentVolumeClaim:
            claimName: longhorn-jellyfin-movies-pvc
        - name: tvshows
          persistentVolumeClaim:
            claimName: longhorn-jellyfin-tvshows-pvc
            claimName: longhorn-jellyfin-movies-pvc
