apiVersion: v1
kind: Service
metadata:
  name: jellyfin-service
  namespace: jellyfin
  annotations:
    metallb.universe.tf/address-pool: default-pool
spec:
  selector:
    app: jellyfin
  type: LoadBalancer
  ports:
    - name: docker-port
      protocol: TCP
      port: 8096
      targetPort: 8096
