linux-server-base:
  name: jackett
  image:
    label: 0.22.856
  port: 9117
  tailscale: true
  resources:
    limits:
      cpu: 1
      memory: 300Mi
    requests:
      cpu: 0.5
      memory: 300Mi
  extraVolumes:
  - name: movies
    claim: longhorn-jellyfin-movies-pvc
    path: /data/movies
  - name: downloads
    claim: longhorn-downloads-2-pvc
    path: /downloads
