apiVersion: v1
kind: Service
metadata:
  name: actual-budget-service
  annotations:
    metallb.universe.tf/address-pool: default-pool
    tailscale.com/expose: "true"
spec:
  selector:
    app: actual-budget
  type: LoadBalancer
  ports:
    - name: docker-port
      protocol: TCP
      port: 443
      targetPort: 5006
