---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
        name: radarr
    spec:
      containers:
      - name: radarr
        image: lscr.io/linuxserver/radarr:{{- .Values.image.label }}
        ports:
        - containerPort: 7878
        volumeMounts:
        - name: config
          mountPath: /config
        - name: movies
          mountPath: /data/movies
        - name: downloads
          mountPath: /downloads
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: longhorn-radarr-config-pvc
        - name: movies
          persistentVolumeClaim:
            claimName: longhorn-jellyfin-movies-pvc
        - name: downloads
          persistentVolumeClaim:
            claimName: longhorn-downloads-2-pvc
