apiVersion: v1
kind: Service
metadata:
  name: radarr-service
  annotations:
    metallb.universe.tf/address-pool: default-pool
spec:
  selector:
    app: radarr
  type: LoadBalancer
  ports:
    - name: docker-port
      protocol: TCP
      port: 7878
      targetPort: 7878
