apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-service
  annotations:
    metallb.universe.tf/address-pool: default-pool
spec:
  selector:
    app: {{ .Values.name }}
  type: LoadBalancer
  ports:
    - name: docker-port
      protocol: TCP
      port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
