---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
        name: {{ .Values.name }}
    spec:
      containers:
      - name: {{ .Values.name }}
        image: lscr.io/linuxserver/{{ .Values.name }}:{{- .Values.image.label }}
        ports:
        - containerPort: {{ .Values.port }}
        volumeMounts:
        - name: config
          mountPath: /config
        - name: movies
          mountPath: /data/movies
        - name: downloads
          mountPath: /downloads
        resources:
{{ .Values.resources | toYaml | indent 10 }}
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: longhorn-{{ .Values.name }}-config-pvc
{{- range $name, $vol := .Values.extraVolumes }}
        - name: {{ $name }}
          persistentVolumeClaim:
            claimName: {{ $vol }}
{{- end }}
