---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jackett
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jackett
  template:
    metadata:
      labels:
        app: jackett
        name: jackett
    spec:
      containers:
      - name: jackett
        image: lscr.io/linuxserver/jackett:{{- .Values.image.label }}
        ports:
        - containerPort: 9117
        volumeMounts:
        - name: config
          mountPath: /config
        - name: data
          mountPath: /data
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: longhorn-jackett-config-pvc
        - name: data
          persistentVolumeClaim:
            claimName: longhorn-jellyfin-pvc
