linux-server-base:
  name: radarr
  image:
    label: 5.14.0
  port: 7878
  tailscale: true
  resources:
    limits:
      cpu: 1
      memory: 300Mi
    requests:
      cpu: 0.5
      memory: 300Mi
  extraVolumes:
    movies: longhorn-jellyfin-movies-pvc
    downloads: longhorn-downloads-2-pvc
