apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - statefulset.yaml
  - lb.yaml

configMapGenerator:
  - name: trilium-config
    literals:
      - TRILIUM_DATA_DIR=/data
